# Generated by Django 3.1.4 on 2020-12-23 02:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataWarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nik', models.CharField(max_length=16)),
                ('nama', models.CharField(max_length=50)),
                ('tempat_lahir', models.CharField(max_length=255)),
                ('tgl_lahir', models.DateField()),
                ('jenis_kelamin', models.CharField(choices=[('LAKI-LAKI', 'LAKI-LAKI'), ('PEREMPUAN', 'PEREMPUAN')], max_length=50)),
                ('gol_darah', models.CharField(max_length=15)),
                ('alamat', models.CharField(max_length=255)),
                ('agama', models.CharField(max_length=10)),
                ('status_perkawinan', models.CharField(choices=[('NIKAH', 'NIKAH'), ('BELUM MENIKAH', 'BELUM MENIKAH')], max_length=50)),
                ('pendidikan', models.CharField(max_length=100)),
                ('pekerjaan', models.CharField(max_length=50)),
                ('kewarganegaraan', models.CharField(max_length=50)),
            ],
        ),
    ]
