# Generated by Django 3.1.4 on 2020-12-23 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datawarga',
            name='gol_darah',
            field=models.CharField(blank=True, max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='datawarga',
            name='jenis_kelamin',
            field=models.CharField(choices=[('PEREMPUAN', 'PEREMPUAN'), ('LAKI-LAKI', 'LAKI-LAKI')], max_length=50),
        ),
    ]
