# Generated by Django 3.1.4 on 2020-12-23 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0002_auto_20201223_0917'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datawarga',
            name='agama',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='datawarga',
            name='status_perkawinan',
            field=models.CharField(choices=[('BELUM MENIKAH', 'BELUM MENIKAH'), ('NIKAH', 'NIKAH')], max_length=50),
        ),
    ]
