# Generated by Django 3.1.4 on 2020-12-23 08:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0003_auto_20201223_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='datawarga',
            name='no_kk',
            field=models.CharField(default='19288281992818', max_length=16),
            preserve_default=False,
        ),
    ]
