# Generated by Django 3.1.4 on 2020-12-28 02:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0004_datawarga_no_kk'),
    ]

    operations = [
        migrations.RenameField(
            model_name='datawarga',
            old_name='alamat',
            new_name='alamat_ktp',
        ),
        migrations.AddField(
            model_name='datawarga',
            name='alamat_sekarang',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='datawarga',
            name='no_telpon',
            field=models.CharField(blank=True, max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='datawarga',
            name='status_perkawinan',
            field=models.CharField(choices=[('NIKAH', 'NIKAH'), ('BELUM MENIKAH', 'BELUM MENIKAH')], max_length=50),
        ),
    ]
