# Generated by Django 3.1.4 on 2021-01-12 18:08

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import warga.models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0005_auto_20201228_0926'),
    ]

    operations = [
        migrations.AddField(
            model_name='datawarga',
            name='kepala_keluarga',
            field=models.BooleanField(default='True'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='datawarga',
            name='no_kk',
            field=models.CharField(max_length=16, unique=True),
        ),
        migrations.AlterField(
            model_name='datawarga',
            name='no_telpon',
            field=models.CharField(max_length=25),
        ),
        migrations.CreateModel(
            name='IuranWarga',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kepala_keluarga', models.CharField(max_length=25)),
                ('tahun', models.IntegerField(validators=[django.core.validators.MinValueValidator(2020), warga.models.max_value_current_year], verbose_name='year')),
                ('januari', models.CharField(blank=True, max_length=15, null=True)),
                ('februari', models.CharField(blank=True, max_length=15, null=True)),
                ('maret', models.CharField(blank=True, max_length=15, null=True)),
                ('april', models.CharField(blank=True, max_length=15, null=True)),
                ('mei', models.CharField(blank=True, max_length=15, null=True)),
                ('juni', models.CharField(blank=True, max_length=15, null=True)),
                ('juli', models.CharField(blank=True, max_length=15, null=True)),
                ('agustus', models.CharField(blank=True, max_length=15, null=True)),
                ('september', models.CharField(blank=True, max_length=15, null=True)),
                ('oktober', models.CharField(blank=True, max_length=15, null=True)),
                ('november', models.CharField(blank=True, max_length=15, null=True)),
                ('desember', models.CharField(blank=True, max_length=15, null=True)),
                ('no_kk', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='kk', to='warga.datawarga', to_field='no_kk')),
            ],
        ),
    ]
