# Generated by Django 3.1.4 on 2021-01-12 18:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warga', '0006_auto_20210113_0108'),
    ]

    operations = [
        migrations.AlterField(
            model_name='datawarga',
            name='status_perkawinan',
            field=models.CharField(choices=[('BELUM MENIKAH', 'BELUM MENIKAH'), ('NIKAH', 'NIKAH')], max_length=50),
        ),
    ]
